mentors/urls.py
from django.urls import path, include
from  . import views
from mentors.views import *
from mentors.views import ResetPasswordView
from django.contrib.auth import views as auth_views
from .views import InscriptionsListView, export_inscriptions_excel

urlpatterns = [
    path('', views.home, name='home'),
    path('tableau_de_bord/', views.boad, name='boad'),
    path('login/', views.Login, name='login'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('editprofile/<int:id>', views.editprofile, name='editprofile'),
    path('createuser/', views.createuser, name='createuser'),
    path('login_user/', views.login_user, name='login_user'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='mentors/password_reset_confirm.html'),
         name='password_reset_confirm'),
    
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='mentors/password_reset_complete.html'),
         name='password_reset_complete'),
    
    path('about/', views.about, name='about'),
    path('bourse-opportunite/', views.bourse_opportunite, name='bourse_opportunite'),
    path('projet/', views.projet, name='projet'),
    path('Mentors/', views.Mentors, name='Mentors'),
    path('orientation/', views.tableau_orientations, name='orientation'),
    path('get_all_ressource/', views.get_all_ressource, name='get_all_ressource'),
    path('add_even/', views.add_even, name='add_even'),
    path('add_ressource/', views.add_ressource, name='add_ressource'),
    path('get_all_forum/', views.get_all_forum, name='get_all_forum'),
    path('add_forum/', views.add_forum, name='add_forum'),
    path('get_all_forum/add_comment/<int:id>/', views.add_comment, name='add_comment'),
    path('get_all_forum/edit_comment/<int:id>/', views.edit_comment, name='edit_comment'),
    path('add_commune/', views.add_commune, name='add_commune'),
    path('add_etablissement/', views.add_etablissement, name='add_etablissement'),
    path('search/', views.search, name='search'),
    path('faq/', views.faq, name='faq'),
    path('newletter/', views.newletter, name='newletter'),
    path('equipe/', views.equipe, name='equipe'),
    path('storie/', views.storie, name='storie'),
    path('osermag/', views.osermag, name='osermag'),
    path('api/api_magazines/', views.api_magazines, name='osermag'),
    path('joint_us/', views.joint_us, name='joint_us'),
    path('joint_us/add', views.adesion, name='adesion'),
    path('demande_ment/add', views.demande_ment, name='demande_ment'),
    path('valider_mentorat/valid/<int:mentorat_id>/', views.valider_mentorat, name='valider_mentorat'),
    path('fermer_mentorat/fermer/<int:mentorat_id>/', views.fermer_mentorat, name='fermer_mentorat'),
    path('complete_profile', views.complete_profile, name='complete_profile'),
    path('mails_personnalisee/', views.mails_personnalisee, name='mails_personnalisee'),
    
    path('mentore_activites/', views.mentore_activites, name='mentore_activites'),
    path('add_mentore_activite/', views.add_activite, name='add_mentore_activite'),
    path('edit_mentore_activite/<id>', views.edit_activite, name='edit_mentore_activite'),
    path('delete_mentore_activite/<id>', views.delete_activite, name='delete_mentore_activite'),
    path('annule_mentore_activite/<id>', views.annule_mentore_activite, name='annule_mentore_activite'),
    path('clos_mentore_activite/<id>', views.clos_mentore_activite, name='clos_mentore_activite'),
    path('valid_mentore_activite/<id>', views.valid_mentore_activite, name='valid_mentore_activite'),
    
    path('agir_avec_nous/', views.agir, name='agir'),
    path('succes/', views.succes, name='succes'),
    path('evensouscription/<int:id>/', views.evensouscription, name='evensouscription'),
    
    path('inscriptions/', InscriptionsListView.as_view(), name='inscriptions_list'),
    path('inscriptions/export/', export_inscriptions_excel, name='export_inscriptions_excel'),
    
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from  django.conf.urls.static import  static
from  django.conf import settings


""" urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('mentors.urls')),
    path('tinymce/', include('tinymce.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) """

urlpatterns = []
if settings.ADMIN_ENABLED is True:
    urlpatterns += [path('admin/', admin.site.urls),]


urlpatterns += [
     path('', include('mentors.urls')),
    path('tinymce/', include('tinymce.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mentors/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.db.models.signals import post_save
from django.dispatch import receiver
import mimetypes
from django.utils import timezone
from django.contrib.auth.signals import user_logged_in,user_logged_out
from django.core.mail import send_mail
from django.conf import settings
from tinymce.models import HTMLField
from tinymce import models as tinymce_models
from datetime import timedelta, date

class Regions(models.Model):
    numero = models.CharField(max_length=1000, blank=True, null=True, verbose_name="Numero d'ordre")
    nomreg = models.CharField(max_length=1000, blank=True, null=True, verbose_name="Nom de la region")
    cheflieu = models.CharField(max_length=1000, blank=True, null=True, verbose_name="Chef lieu")
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    
    class Meta:
        verbose_name = "Regions"
        verbose_name_plural = "Region"
        
    def __str__(self):
        return self.nomreg




class Provinces(models.Model):
    numero = models.CharField(max_length=1000, blank=True, null=True,verbose_name="Numero d'ordre")
    nomprov = models.CharField(max_length=500, blank=True, null=True, verbose_name="Nom de la province")
    region = models.ForeignKey(Regions, blank=True, null=True, on_delete=models.CASCADE, verbose_name="Region")
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)

    
    class Meta:
        verbose_name = "Provinces"
        verbose_name_plural = "Province"
        
    def __str__(self):
        return self.nomprov
    



class Communes(models.Model):
    nom_commune = models.CharField(max_length=1000, blank=True, null=True, verbose_name="Nom de la commune")
    province = models.ForeignKey(Provinces, blank=True, null=True, on_delete=models.CASCADE,verbose_name="Province")
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    
    def __str__(self):
        return self.nom_commune
    
class Status(models.Model):
    statut = models.CharField(max_length=100, blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)

    def __str__(self):
        return self.statut

class Etablissement(models.Model):
    libelle = models.CharField(max_length=200, blank=True, null=True)
    statut = models.ForeignKey(Status, blank=True, null=True, on_delete=models.CASCADE)
    commune = models.ForeignKey(Communes, blank=True, null=True, on_delete=models.CASCADE)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)

    def __str__(self):
        return self.libelle




class Ressources(models.Model):
    titre = models.CharField(max_length=50, null=True, blank=True, verbose_name="Titre")
    description = models.TextField(blank=True, null=True, verbose_name="Description")
    ressource = models.FileField(upload_to='Fichiers/', null=True, blank=True)
    owner = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)

    
    def __str__(self):
        return self.titre
    
    
    def get_mime_type(self):
        if self.ressource:
            return mimetypes.guess_type(self.ressource.path)[0]
        else:
            return None
        
        
class Forum(models.Model):
    titre = models.CharField(max_length=50, null=True, blank=True, verbose_name="Titre")
    description = models.TextField(blank=True, null=True, verbose_name="Description")
    fichier = models.FileField(upload_to='forum_img/', null=True, blank=True, verbose_name="Image illustrative")
    initiateur = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    
    IMAGE_MAX_SIZE = (370, 260)
    
    def resize_image(self):
        if self.fichier:
            image = Image.open(self.fichier)
            image.thumbnail(self.IMAGE_MAX_SIZE)
            # sauvegarde de l’image redimensionnée dans le système de fichiers
            # ce n’est pas la méthode save() du modèle !
            image.save(self.fichier.path)
        
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.fichier:
            self.resize_image()
        
        
    def __str__(self):
        return self.titre
    
    
    @classmethod
    def recents(cls):
        seven_days_ago = date.today() - timedelta(days=2)
        return cls.objects.filter(created__gte=seven_days_ago).count()

        
        
class ForumComment(models.Model):
    comment = models.TextField(blank=True, null=True, verbose_name="Commentaire")
    forum = models.ForeignKey(Forum, blank=True, null=True, on_delete=models.CASCADE)
    user_comment = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    comment_views = models.IntegerField(default=0)
    comment_likes = models.IntegerField(default=0)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    
        
        
    @classmethod
    def add_like(cls, comment_id):
        try:
            comment = cls.objects.get(pk=comment_id)
            comment.comment_likes += 1
            comment.save(update_fields=['comment_likes'])
            return comment.comment_likes
        except cls.DoesNotExist:
            return None

    def __str__(self):
        return self.comment 
    
    
class Badge(models.Model):
    classe_badge = models.CharField(max_length=100, blank=True, null=True)
    badge = models.FileField(upload_to='images/', null=True, blank=True)
    description = models.TextField(blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    IMAGE_MAX_SIZE = (39, 60)
    
    def resize_image(self):
        if self.badge:
            image = Image.open(self.badge)
            image.thumbnail(self.IMAGE_MAX_SIZE)
            image.save(self.badge.path)
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.badge:
            self.resize_image()
        
    
    
    def __str__(self):
        return self.classe_badge
    
    
class CategorieFormation(models.Model):
    libelle = models.CharField(max_length=100, blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    
    def __str__(self):
        return self.libelle
    
class Domaine(models.Model):
    libelle = models.CharField(max_length=100, blank=True, null=True)
    categorie = models.ForeignKey(CategorieFormation, blank=True, null=True, on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    
    
    def __str__(self):
        return self.libelle



        
class Type_oriention(models.Model):
    libelle = models.CharField(max_length=100, blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    
    def __str__(self):
        return self.libelle
    
    
class Objectif_Accademique(models.Model):
    libelle = models.CharField(max_length=100, blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    
    def __str__(self):
        return self.libelle
    
    
class Cannaux_Communication(models.Model):
    libelle = models.CharField(max_length=100, blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    
    def __str__(self):
        return self.libelle



class Frequence_Echange(models.Model):
    libelle = models.CharField(max_length=100, blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    
    def __str__(self):
        return self.libelle
    
    

class Cannaux_Connaissance(models.Model):
    libelle = models.CharField(max_length=100, blank=True, null=True)
    created = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    modified = models.DateField(blank=True, null=True, auto_created=True, auto_now_add=True)
    
    def __str__(self):
        return self.libelle



class Filiere_Serie(models.Model):

mentors/templates/mentors/add_ressource.html
{% extends "base.html" %}
{% load static %}
{% block main %}
<!-- Style personnalisé pour le formulaire -->
<style>
  :root {
    --primary-color: #0080ff;
    --secondary-color: #0080ff;
    --accent-color: #f72585;
    --light-color: #f8f9fa;
    --dark-color: #212529;
    --success-color: #4cc9f0;
    --warning-color: #f8961e;
    --danger-color: #f94144;
    --border-radius: 12px;
    --box-shadow: 0 8px 30px rgba(0, 0, 0, 0.12);
  }
  
  .form-section {
    background-color: #f9f9fb;
    min-height: 100vh;
    padding: 3rem 0;
  }
  
  .form-header {
    text-align: center;
    margin-bottom: 2.5rem;
  }
  
  .form-title {
    font-weight: 700;
    color: var(--dark-color);
    margin-bottom: 0.5rem;
    font-size: 2rem;
  }
  
  .form-subtitle {
    color: #6c757d;
    font-weight: 400;
    font-size: 1.1rem;
    max-width: 600px;
    margin: 0 auto;
  }
  
  .form-container {
    background-color: white;
    border-radius: var(--border-radius);
    box-shadow: var(--box-shadow);
    padding: 2.5rem;
    margin-bottom: 2rem;
    position: relative;
    overflow: hidden;
  }
  
  .form-container::before {
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 5px;
    background: linear-gradient(90deg, var(--primary-color), var(--secondary-color));
  }
  
  .form-label {
    font-weight: 600;
    font-size: 0.9rem;
    color: var(--dark-color);
    margin-bottom: 0.5rem;
    display: block;
  }
  
  .form-control {
    border-radius: var(--border-radius);
    border: 1px solid #e9ecef;
    padding: 0.8rem 1rem;
    font-size: 1rem;
    transition: all 0.3s ease;
    width: 100%;
    background-color: #f8f9fa;
  }
  
  .form-control:focus {
    outline: none;
    border-color: var(--primary-color);
    box-shadow: 0 0 0 3px rgba(67, 97, 238, 0.15);
    background-color: white;
  }
  
  textarea.form-control {
    min-height: 120px;
    resize: vertical;
  }
  
  .form-text {
    font-size: 0.85rem;
    color: #6c757d;
    margin-top: 0.3rem;
  }
  
  .form-group {
    margin-bottom: 1.5rem;
  }
  
  .form-group:last-child {
    margin-bottom: 0;
  }
  
  .form-actions {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-top: 2rem;
  }
  
  .btn {
    border-radius: var(--border-radius);
    padding: 0.8rem 2rem;
    font-weight: 600;
    font-size: 1rem;
    transition: all 0.3s ease;
    border: none;
    cursor: pointer;
  }
  
  .btn-primary {
    background: linear-gradient(135deg, var(--primary-color), var(--secondary-color));
    color: white;
  }
  
  .btn-primary:hover {
    transform: translateY(-3px);
    box-shadow: 0 7px 14px rgba(67, 97, 238, 0.2);
  }
  
  .btn-outline {
    background-color: transparent;
    border: 1px solid #e9ecef;
    color: #6c757d;
  }
  
  .btn-outline:hover {
    background-color: #f8f9fa;
    color: var(--dark-color);
  }
  
  .form-icon {
    margin-right: 0.5rem;
  }
  
  .form-error {
    color: var(--danger-color);
    font-size: 0.85rem;
    margin-top: 0.3rem;
    display: block;
  }
  
  .upload-container {
    position: relative;
    border: 2px dashed #e9ecef;
    border-radius: var(--border-radius);
    padding: 2rem;
    text-align: center;
    transition: all 0.3s ease;
    cursor: pointer;
    margin-bottom: 1rem;
  }
  
  .upload-container:hover {
    border-color: var(--primary-color);
    background-color: rgba(67, 97, 238, 0.03);
  }
  
  .upload-icon {
    font-size: 2.5rem;
    color: var(--primary-color);
    margin-bottom: 1rem;
  }
  
  .upload-text {
    font-weight: 600;
    color: var(--dark-color);
    margin-bottom: 0.5rem;
  }
  
  .upload-subtext {
    font-size: 0.9rem;
    color: #6c757d;
  }
  
  .upload-input {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    opacity: 0;
    cursor: pointer;
  }
  
  .file-preview {
    display: none;
    text-align: left;
    padding: 1rem;
    background-color: #f8f9fa;
    border-radius: var(--border-radius);
    margin-top: 1rem;
  }
  
  .file-preview.active {
    display: block;
    animation: fadeIn 0.3s ease;
  }
  
  .file-info {
    display: flex;
    align-items: center;
  }
  
  .file-icon {
    font-size: 1.5rem;
    margin-right: 1rem;
    color: var(--primary-color);
  }
  
  .file-details {
    flex: 1;
  }
  
  .file-name {
    font-weight: 600;
    margin-bottom: 0.2rem;
    color: var(--dark-color);
  }
  
  .file-size {
    font-size: 0.85rem;
    color: #6c757d;
  }
  
  .file-remove {
    color: var(--danger-color);
    cursor: pointer;
    font-size: 1.2rem;
    transition: all 0.2s ease;
  }
  
  .file-remove:hover {
    transform: scale(1.2);
  }
  
  .back-link {
    display: inline-flex;
    align-items: center;
    color: #6c757d;
    font-weight: 600;
    text-decoration: none;
    transition: all 0.2s ease;
    margin-bottom: 1.5rem;
  }
  
  .back-link:hover {
    color: var(--primary-color);
  }
  
  .back-icon {
    margin-right: 0.5rem;
  }
  
  /* Animations */
  @keyframes fadeIn {
    from { opacity: 0; transform: translateY(10px); }
    to { opacity: 1; transform: translateY(0); }
  }
  
  .form-container {
    animation: fadeIn 0.5s ease;
  }
  
  /* Responsive Design */
  @media (max-width: 768px) {
    .form-container {
      padding: 1.5rem;
    }
    
    .form-actions {
      flex-direction: column;
    }
    
    .btn {
      width: 100%;
      margin-bottom: 1rem;
    }
    
    .form-actions .btn:last-child {
      margin-bottom: 0;
    }
  }
</style>

<div class="form-section">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <!-- En-tête du formulaire -->
        <div class="form-header">
          <p class="form-subtitle">Partagez vos ressources avec la communauté en remplissant ce formulaire</p>
        </div>
        
        <!-- Formulaire d'ajout -->
        <div class="form-container">
          <form method="post" enctype="multipart/form-data" id="document-form">
            {% csrf_token %}
            
            <!-- Champ du titre -->
            <div class="form-group">
              <label for="id_titre" class="form-label">Titre du document</label>
              {{ form.titre.errors }}
              {{ form.titre }}
              <small class="form-text">Choisissez un titre descriptif et concis</small>
            </div>
            
            <!-- Champ de description -->
            <div class="form-group">
              <label for="id_description" class="form-label">Description</label>
              {{ form.description.errors }}
              {{ form.description }}
              <small class="form-text">Décrivez brièvement le contenu du document</small>
            </div>
            
            <!-- Zone de dépôt de fichier -->
            <div class="form-group">
              <label class="form-label">Fichier</label>
              <div class="upload-container" id="upload-zone">
                <i class="fas fa-cloud-upload-alt upload-icon"></i>
                <h4 class="upload-text">Glissez votre fichier ici</h4>
                <p class="upload-subtext">ou cliquez pour sélectionner un fichier</p>
                {{ form.ressource.errors }}
                {{ form.ressource }}
                <small class="form-text">Format acceptés : PDF, Word, Excel, PowerPoint, images, vidéos</small>
              </div>
              
              <!-- Prévisualisation du fichier -->
              <div class="file-preview" id="file-preview">
                <div class="file-info">
                  <i class="fas fa-file file-icon" id="preview-icon"></i>
                  <div class="file-details">
                    <div class="file-name" id="file-name">document.pdf</div>
                    <div class="file-size" id="file-size">0 KB</div>
                  </div>
                  <i class="fas fa-times file-remove" id="remove-file"></i>
                </div>
              </div>
            </div>
            
            <!-- Boutons d'action -->
            <div class="form-actions">
              <a href="{% url 'get_all_ressource' %}" class="btn btn-outline">
                <i class="fas fa-times form-icon"></i>Annuler
              </a>
              <button type="submit" class="btn btn-primary">
                <i class="fas fa-cloud-upload-alt form-icon"></i>Ajouter le document
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Script pour la gestion du formulaire -->
<script>
document.addEventListener('DOMContentLoaded', function() {
  // Éléments du formulaire
  const form = document.getElementById('document-form');
  const uploadZone = document.getElementById('upload-zone');
  const fileInput = document.querySelector('input[type="file"]');
  const filePreview = document.getElementById('file-preview');
  const fileName = document.getElementById('file-name');
  const fileSize = document.getElementById('file-size');
  const fileIcon = document.getElementById('preview-icon');
  const removeFile = document.getElementById('remove-file');
  
  // Appliquer les classes aux éléments du formulaire
  const titleInput = document.getElementById('id_titre');
  const descriptionInput = document.getElementById('id_description');
  
  if (titleInput) {
    titleInput.classList.add('form-control');
    titleInput.setAttribute('placeholder', 'Titre du document');
  }
  
  if (descriptionInput) {
    descriptionInput.classList.add('form-control');
    descriptionInput.setAttribute('placeholder', 'Description détaillée du document');
  }
  
  if (fileInput) {
    fileInput.classList.add('upload-input');
  }
  
  // Fonction pour formater la taille du fichier
  function formatFileSize(bytes) {
    if (bytes === 0) return '0 Bytes';
    
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
  }
  
  // Fonction pour déterminer l'icône en fonction du type de fichier
  function getFileIcon(fileName) {
    const extension = fileName.split('.').pop().toLowerCase();
    
    if (['jpg', 'jpeg', 'png', 'gif', 'svg', 'webp'].includes(extension)) {
      return 'fas fa-file-image';
    } else if (['pdf'].includes(extension)) {
      return 'fas fa-file-pdf';
    } else if (['doc', 'docx'].includes(extension)) {
      return 'fas fa-file-word';
    } else if (['xls', 'xlsx', 'csv'].includes(extension)) {
      return 'fas fa-file-excel';
    } else if (['ppt', 'pptx'].includes(extension)) {
      return 'fas fa-file-powerpoint';
    } else if (['mp4', 'webm', 'mov', 'avi'].includes(extension)) {
      return 'fas fa-file-video';
    } else if (['mp3', 'wav', 'ogg'].includes(extension)) {
      return 'fas fa-file-audio';
    } else if (['zip', 'rar', '7z', 'tar', 'gz'].includes(extension)) {
      return 'fas fa-file-archive';
    } else {
      return 'fas fa-file';
    }
  }
  
  // Lorsqu'un fichier est sélectionné
  if (fileInput) {
    fileInput.addEventListener('change', function(e) {
      if (this.files && this.files[0]) {
        const file = this.files[0];
        
        // Mettre à jour la prévisualisation
        fileName.textContent = file.name;
        fileSize.textContent = formatFileSize(file.size);
        fileIcon.className = getFileIcon(file.name);
        
        // Afficher la prévisualisation
        filePreview.classList.add('active');
        uploadZone.style.borderColor = 'var(--primary-color)';
      }
    });
  }
  
  // Supprimer le fichier
  if (removeFile) {
    removeFile.addEventListener('click', function() {
      if (fileInput) {
        fileInput.value = '';
        filePreview.classList.remove('active');
        uploadZone.style.borderColor = '#e9ecef';
      }
    });
  }
  
  // Glisser-déposer
  if (uploadZone) {
    ['dragenter', 'dragover', 'dragleave', 'drop'].forEach(eventName => {
      uploadZone.addEventListener(eventName, preventDefaults, false);
    });
    
    function preventDefaults(e) {
      e.preventDefault();
      e.stopPropagation();
    }
    
    ['dragenter', 'dragover'].forEach(eventName => {
      uploadZone.addEventListener(eventName, highlight, false);
    });
    
    ['dragleave', 'drop'].forEach(eventName => {
      uploadZone.addEventListener(eventName, unhighlight, false);
    });
    
    function highlight() {
      uploadZone.style.borderColor = 'var(--primary-color)';
      uploadZone.style.backgroundColor = 'rgba(67, 97, 238, 0.05)';
    }
    
    function unhighlight() {
      uploadZone.style.borderColor = '#e9ecef';
      uploadZone.style.backgroundColor = 'transparent';
    }
    
    uploadZone.addEventListener('drop', handleDrop, false);
    
    function handleDrop(e) {
      const dt = e.dataTransfer;
      const files = dt.files;
      
      if (fileInput && files.length > 0) {
        fileInput.files = files;
        
        // Déclencher l'événement change
        const event = new Event('change');
        fileInput.dispatchEvent(event);
      }
    }
  }
});
</script>
{% endblock main %}

mentors/templates/mentors/password_reset_complete.html
{% extends "base.html" %}
{% block main %}
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="alert alert-info">
                        Votre mot de passe à été reinitialiser. <a href="{% url 'login' %}">Se connecter </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock main %}